# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e73c51fafb6249c6ddc38e7c3a8c29e5d27ef120f0e256b1cb2a3b5beff97a53b566df830875996708544f9ca6f362ad7e99963b09746db0e8d1ab88e13b9ba

test:
  secret_key_base: 9ca070a818010a00ae9cda4c585121f8c068ebd29731a43a2078ca1102134ce22f18df8836e8322d08370b9b7034f1228917f42444fbae777206b8bec8760a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
